### ISSUE TITLE
RU09 Agregar Pulsores

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#10]
Deben poder agregarse pulsores.
- [x] Iteración 1
  - [x] RS Implementar lógica interna Pulsor #19  
  - [X] RS Implementar interfaz gráfica Pulsor #20

**Comment by moishernadez** [comment]
[ ] Iteración 1

[ ] RS Implementar lógica interna Pulsor
[ ] RS Implementar interfaz gráfica Pulsor

**Comment by zero1712** [comment]
RS Agregar interfaz gráfica componente Pulsor #20

**Comment by zero1712** [comment]
RS Implementar logica interna componente Pulsor #19

**Comment by m4droid** [comment]
Requisito aceptado por el cliente.
