### ISSUE TITLE
RU08 - Agregarse reloj

### ISSUE THREAD

**Issue by sebitoelcheater** [m4droid/logisim#11]
Deben poder agregar relojes.
Iteración 1
- [x] Agregar lógica interna reloj #21 
- [x] Agregar interfaz gráfica reloj #22

**Comment by moishernadez** [comment]
[ ] Iteración 1

[ ] Agregar lógica interna reloj
[ ] Agregar interfaz gráfica reloj

**Comment by storress** [comment]
Actualizado e issue y cambiado el formato

**Comment by mariocesarc** [comment]
listo
