### ISSUE TITLE
RU12 Importar circuito

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#16]
El sistema debe permitir importar un circuito hecho en la interfaz tradicional de logisim
[ ] Iteración 1
[ ]  Crear botón para importar circuito 
[ ]  Agregar comportamiento al botón, de modo de permitir agregar un componente en la ventana de componentes

**Comment by m4droid** [comment]
Este feature se considera completado dado que los componentes fueron implementados ocupando las clases de Logisim.

**Comment by m4droid** [comment]
Requisito aceptado por el cliente.
