### ISSUE TITLE
RS Agregar interfaz gráfica componente Protoboard

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#17]
- [x] Iteración 1
  - [X] RS01 Mostrar en la misma ventana un panel de componentes
  - [X] RS02 Mejorar usabilidad de la protoboard

**Comment by m4droid** [comment]
![captura de pantalla 2015-10-29 a las 1 11 50 p m](https://cloud.githubusercontent.com/assets/991449/10824307/acba1120-7e3e-11e5-9052-602b84788308.png)

Existe un problema de usabilidad de la protoboard propuesta. Al momento de realizar una conexión desde las pistas de alimentación se conectan ambos puertos (positivo y negativo) como ve en la imagen. Se debe acordar con el cliente una solución.

**Comment by m4droid** [comment]
El cliente determina que es deseable arreglar los problemas de usabilidad de Logisim para la última entrega. Si no es posible realizarlo se debe plantear una alternativa. En este caso, ocupar doble espaciado de los puertos de alimentación.

**Comment by mariocesarc** [comment]
![screenshot from 2015-11-21 02 54 27](https://cloud.githubusercontent.com/assets/14824391/11317062/ac07b5cc-8ffd-11e5-839e-a3a3a3bab0ef.png)
propuesta de solución: el cable no se conecta con el pin a menos que se conecte desde los extremos del cable
