### ISSUE TITLE
RS Agregar interfaz gráfica componente Pulsor

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#20]
- [X] Iteracion 1
  - [X] Agregar componente en el panel dentro de la carpeta protosim
  - [X] Agregar ícono
  - [X] Agregar visualización en el panel

**Comment by zero1712** [comment]
Referencia al commit: 
https://github.com/m4droid/logisim/commit/09fddf1843ec26fc773d728a0d798f2c9a6d5d3a

**Comment by zero1712** [comment]
Referencia al commit https://github.com/m4droid/logisim/commit/b312f8e895bfa2864c05fcde60ca977d2dd22b2e
