### ISSUE TITLE
RS Implementar logica interna componente Reloj

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#21]
RU08 - Agregarse relojes #11 
- [x] Iteracion 1
  - [x] Implementarla parte lógica sobre la pieza RELOJ (que ya está creada). De forma que se pueda observar directamente en la interfaz gráfica su funcionamiento.
- [x] Iteracion 2
  - [x] modificar la lógica del componente RELOJ de modo que tenga que ser conectado a una pila para que funcione
  - [x] modificar la lógica del componente RELOJ de modo que utilice la interfaz ProtoValue para representar valores de voltaje en la protoboard.

**Comment by mariocesarc** [comment]
listo
