### ISSUE TITLE
RS Agregar interfaz gráfica componente Reloj

### ISSUE THREAD

**Issue by moishernadez** [m4droid/logisim#22]
RU08 - Agregarse relojes #11 
- [x] Iteracion 1
  - [x] Agregar reloj al panel dentro de la carpeta Protosim
  - [x] Incluir ícono de un reloj
  - [x] Incluir visualización en el panel
- [x] Iteracion 2
  - [x] Agregar Puertos

**Comment by moishernadez** [comment]
Listo

**Comment by storress** [comment]
No tiene puertos para conectar

**Comment by moishernadez** [comment]
Puertos agregados
