### ISSUE TITLE
RS Implementar logica interna componente LED

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#24]
- [x] Iteración 1
  - [x] Sincronizar con lógica. (Luz prendida o apagada)
- [x] Iteración 2
  - [x] Unificar el funcionamiento con los otros componentes 
  - [x] Crear tests

**Comment by zero1712** [comment]
La logica del Led se cumple en el siguiente commit https://github.com/m4droid/logisim/commit/d9feaf0a515cdd384193e4b8f941a9e4c8f7922d  pero aun no cierro el issue ya que necesitamos ver como interactua con otras piezas.

**Comment by storress** [comment]
Actualizada la descripción del Issue para tener mejor compresión del avance

**Comment by zero1712** [comment]
Se probo el led con diferentes circuitos y el circuito final, 
Led funciona correctamente, por lo que proceso a cerrar el issue.
