### ISSUE TITLE
RS Agregar interfaz gráfica componente LED

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#25]
- [x] Iteracion 1
  - [x] Agregar led al panel dentro de la carpeta Protosim
  - [x] Incluir ícono de un led
  - [x] Incluir visualización en el panel

**Comment by storress** [comment]
Se agrega Iteracion 2 para finalizar la sincronización con la logica para "prender" el LED o "apagarlo" dependiendo de si le llega corriente o no

**Comment by m4droid** [comment]
La iteración 2 es parte de https://github.com/m4droid/logisim/issues/24
