### ISSUE TITLE
RS Implementar logica interna componente AND

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#30]
RU03 Compuertas lógicas #9
- [x] Iteracion 1
  - [x] Implementarla parte lógica sobre la pieza AND (que ya está creada). De forma que se pueda observar directamente en la interfaz gráfica su funcionamiento.
- [x] Iteracion 2
  - [x] modificar la lógica del componente AND de modo que tenga que ser conectado a una pila para que funcione
  - [x] modificar la lógica del componente AND de modo que utilice la interfaz ProtoValue para representar valores de voltaje en la protoboard. 
- [x] Iteracion 3
  - [x] modificación de la pieza AND para que cumpla el estándar comercial.
  - [x] modificación de los tests componente AND para adaptación a los nuevos cambios

**Comment by m4droid** [comment]
https://github.com/m4droid/logisim/commit/e1f382262ebfa32f62e98bd58411829dfb696204

**Comment by m4droid** [comment]
Se debe cambiar la lógica del chip. De acuerdo a las especificaciones del cliente, bajo 2.5v se considera como ausencia de corriente.

**Comment by m4droid** [comment]
No se cambiaron los tests: https://travis-ci.org/m4droid/logisim/builds/92839042

**Comment by moishernadez** [comment]
listo

**Comment by moishernadez** [comment]
listo
