### ISSUE TITLE
RS Agregar interfaz gráfica componente OR

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#32]
RU03 Compuertas lógicas #9 
- [x] Iteracion 1
  - [x] Agregar OR al panel dentro de la carpeta Protosim
  - [x] Incluir ícono de un OR
  - [x] Incluir visualización en el panel
- [x] Iteracion 2
  - [x] Agregar Puertos

**Comment by moishernadez** [comment]
listo

**Comment by storress** [comment]
No tiene puertos para conectar

**Comment by moishernadez** [comment]
Puertos agregados
