### ISSUE TITLE
RS Implementar logica interna componente OR

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#34]
RU03 Compuertas lógicas #9 
- [x] Iteracion 1
  - [x] Agregar OR al panel dentro de la carpeta Protosim
  - [x] Incluir ícono de un OR
  - [x] Incluir visualización en el panel
- [x] Iteracion 2
  - [x] modificar la lógica del componente AND de modo que tenga que ser conectado a una pila para que funcione

**Comment by moishernadez** [comment]
listo
