### ISSUE TITLE
RS Implementar logica interna componente NAND

### ISSUE THREAD

**Issue by zero1712** [m4droid/logisim#36]
RU03 Compuertas lógicas #9
- [x] Iteracion 1
  - [x] Agregar lógica interna básica 
- [x] Iteracion 2
  - [x] modificar la lógica del componente NAND de modo que utilice la interfaz ProtoValue para representar valores de voltaje en la protoboard.

**Comment by moishernadez** [comment]
listo

**Comment by moishernadez** [comment]
listo
