### ISSUE TITLE
RS Agregar interfaz gráfica componente NAND

### ISSUE THREAD

**Issue by zero1712** [m4droid/logisim#37]
RU03 Compuertas lógicas #9 
- [x] Iteracion 1
  - [x] Agregar NAND al panel dentro de la carpeta Protosim
  - [x] Incluir ícono de un NAND
  - [x] Incluir visualización en el panel
- [x] Iteracion 2
  - [x] Agregar Puertos

**Comment by moishernadez** [comment]
Listo

**Comment by storress** [comment]
No tiene puertos para conectar

**Comment by moishernadez** [comment]
Puertos agregados
