### ISSUE TITLE
RS Implementar logica interna Generador de Voltaje

### ISSUE THREAD

**Issue by storress** [m4droid/logisim#39]
Implementar lógica interna del generador del voltaje o pila. Debe arrojar 0 volts por un puerto, y 5 volts por el otro.
- [x] Iteración 1
  - [x] Implementar comportamiento lógico.
- [x] Iteración 2
  - [x] Incluir tests

**Comment by storress** [comment]
Requisito de #4

**Comment by moishernadez** [comment]
listo
