### ISSUE TITLE
RS Implementar logica interna componente FLIP FLOP

### ISSUE THREAD

**Issue by mariocesarc** [m4droid/logisim#44]
RU03 Compuertas lógicas #9

**Comment by zero1712** [comment]
Ya que se esta respetando estandar comercial 74 , el flip debera ser implementado acorde a la serie 7474  , el siguiente enlace muestra como debe ser la implementacion: http://www.alessioviti.com/lcdprojects/datasheet/7474.gif

**Comment by zero1712** [comment]
Referencia al commit https://github.com/m4droid/logisim/commit/110221c29e55e59de21380c7a5084d6c7466187f

**Comment by zero1712** [comment]
El circuito flip flop se probo con diferentes circuitos, y no se encontraron problemas en el funcionamiento,
El circuito flip flop se encuentra funcionando, por lo que procedo a cerrar el issue.
