### ISSUE TITLE
RS Agregar interfaz gráfica de las piezas

### ISSUE THREAD

**Issue by zero1712** [m4droid/logisim#47]
Funcionalidad que permite visualizar los componentes en la interfaz de logisim
- [x] Interfaz gráfica  del pulsador 
- [x] Interfaz gráfica del reloj 
- [x] Interfaz gráfica de LEDs
- [x] Interfaz gráfica del FLIP FLOP
- [x] Interfaz gráfica de la resistencia
- [x] Interfaz gráfica de la compuerta AND
- [x] Interfaz gráfica de la compuerta OR
- [x] Interfaz gráfica de la compuerta NOT
- [x] Interfaz gráfica de la compuerta NAND

**Comment by storress** [comment]
Agregado el formato del Issue y marcado el avance actual del issue.

Se cierra el Issue ya que se completó
