### ISSUE TITLE
RS05 Fácil de usar

### ISSUE THREAD

**Issue by zero1712** [m4droid/logisim#49]
El programa debe ser fácil de usar. Se entiende que una persona (usuario) sea capaz de crear un archivo nuevo, diseñar un circuito con una protoboard y no tenga problemas con utilizar el programa.

Ref:
RU10 Arrastrar y soltar componentes #7 
RU11 Interfaz sencilla #45

**Comment by storress** [comment]
Ambiguo

**Comment by m4droid** [comment]
La implementación actual utiliza la interfaz de Logisim, por lo que se considera que es consistente con la usabilidad del software.
