### ISSUE TITLE
RU03 Compuertas lógicas

### ISSUE THREAD

**Issue by maxkauer** [m4droid/logisim#9]
Deben poder agregarse las siguientes puertas lógicas: FLIPFLOP, AND, OR, NAND y NOT.
- [x] Agregar pieza AND 
  - [x] Logica Interna #30
  - [x] Interfaz grafica #31
- [x] Agregar pieza NAND 
  - [x] Logica Interna #36
  - [x] Interfaz grafica #37
- [x] Agregar pieza NOT 
  - [x] Logica Interna #35
  - [x] Interfaz grafica #33
- [x] Agregar pieza OR
  - [x] Logica Interna #34
  - [x] Interfaz grafica #32
- [x] Agregar pieza FLIP FLOP
  - [x] Logica Interna #44
  - [x] Interfaz grafica #42

**Comment by zero1712** [comment]
Se usara como estandar la serie 7400 para el diseño de las compuertas logicas
https://es.wikipedia.org/wiki/Serie_7400

**Comment by storress** [comment]
Se corrio este comentario para arriba

**Comment by m4droid** [comment]
Requisito aceptado por el cliente.
